name: Update Phrases Daily

on:
  schedule:
    - cron: "0 12 * * *"  # Every day at 12:00 UTC
  workflow_dispatch:      # Optional: allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
            token: ${{ secrets.GH_PAT}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
            YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python scrape.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/phrases.json output/failed.json || true
          git diff --quiet && git diff --staged --quiet || git commit -m "auto update phrases.json"
          git push
